import { Suspense } from 'react';
import Header from './components/Header';
import './globals.css';
import { Mulish } from 'next/font/google';
import Loading from './Loading';

const mulish = Mulish({
	subsets: ['latin'],
	weight: ['300', '400', '500', '600', '700', '800', '900'],
});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={mulish.className}>
				<Header />
				<Suspense fallback={<Loading />}>{children}</Suspense>
			</body>
		</html>
	);
}
